#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D uEquirect;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2DArray uFaces;

vec3 faceDirection(uint face, vec2 uv) {
    switch(face) {
        case 0u: return vec3( 1.0, -uv.y, -uv.x); // +X
        case 1u: return vec3(-1.0, -uv.y,  uv.x); // -X
        case 2u: return vec3( uv.x,  1.0,  uv.y); // +Y
        case 3u: return vec3( uv.x, -1.0, -uv.y); // -Y
        case 4u: return vec3( uv.x, -uv.y,  1.0); // +Z
        case 5u: return vec3(-uv.x, -uv.y, -1.0); // -Z
    }
    return vec3(0.0);
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID);
    ivec2 sz = imageSize(uFaces).xy;
    if (any(greaterThanEqual(id.xy, sz))) return;

    vec2 uv = (vec2(id.xy) + 0.5) / vec2(sz) * 2.0 - 1.0;
    vec3 d  = normalize(faceDirection(uint(id.z), uv));

    vec2 e = vec2(atan(d.z, d.x) / 6.28318530718 + 0.5,
            acos(clamp(d.y, -1.0, 1.0)) / 3.14159265359);

    imageStore(uFaces, id, textureLod(uEquirect, e, 0.0));
}