#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform samplerCube uSkybox;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2DArray uIrradiance;

const float PI = 3.14159265359;
const float dPhi = 0.025;
const float dTheta = 0.025;

vec3 faceDirection(uint face, vec2 uv) {
    switch(face) {
        case 0u: return vec3( 1.0, -uv.y, -uv.x); // +X
        case 1u: return vec3(-1.0, -uv.y,  uv.x); // -X
        case 2u: return vec3( uv.x,  1.0,  uv.y); // +Y
        case 3u: return vec3( uv.x, -1.0, -uv.y); // -Y
        case 4u: return vec3( uv.x, -uv.y,  1.0); // +Z
        case 5u: return vec3(-uv.x, -uv.y, -1.0); // -Z
    }
    return vec3(0.0);
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID);
    ivec2 sz = imageSize(uIrradiance).xy;
    if (any(greaterThanEqual(id.xy, sz))) return;

    vec2 uv = (vec2(id.xy) + 0.5) / vec2(sz) * 2.0 - 1.0;
    vec3 N = normalize(faceDirection(uint(id.z), uv));

    vec3 up = abs(N.y) < 0.999 ? vec3(0.0, 1.0, 0.0) : vec3(0.0, 0.0, 1.0);
    vec3 T = normalize(cross(up, N));
    vec3 B = cross(N, T);

    vec3 sum = vec3(0.0);
    float n = 0.0;
    for (float phi = 0.0; phi < 2.0 * PI; phi += dPhi) {
        for (float theta = 0.0; theta < 0.5 * PI; theta += dTheta) {
            vec3 tanSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            vec3 dir = tanSample.x * T + tanSample.y * B + tanSample.z * N;

            sum += textureLod(uSkybox, dir, 0.0).rgb * cos(theta) * sin(theta);
            n += 1.0;
        }
    }

    imageStore(uIrradiance, id, vec4(PI * sum / n, 1.0));
}